"use client";
import { useEffect, useState } from "react";
import { createSupabaseBrowserClient } from "@/lib/supabase/client";
import { useRouter } from "next/navigation";

export default function UpdatePasswordPage(){const router=useRouter();const [ready,setReady]=useState(false);const [pending,setPending]=useState(false);const [message,setMessage]=useState("");
  useEffect(()=>{const supabase=createSupabaseBrowserClient();supabase.auth.getSession().then(({data})=>setReady(Boolean(data.session)));const {data}=supabase.auth.onAuthStateChange((_event,session)=>setReady(Boolean(session)));return()=>data.subscription.unsubscribe();},[]);
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setPending(true);setMessage("");const form=new FormData(event.currentTarget);const password=String(form.get("password")||"");const confirmation=String(form.get("confirmation")||"");if(password!==confirmation){setMessage("Passwords do not match.");setPending(false);return;}const {error}=await createSupabaseBrowserClient().auth.updateUser({password});if(error){setMessage(error.message);setPending(false);return;}await createSupabaseBrowserClient().auth.signOut();router.push("/login?message=Password+created.+Sign+in+to+continue");router.refresh();}
  return <div className="login-shell"><div className="login-card"><div className="brand" style={{color:"var(--ink)",padding:0,marginBottom:28}}><span className="brand-mark">A</span>ApplyIQ</div><div className="eyebrow">Secure account setup</div><h1>Create your password</h1><p className="subtle">Choose a unique password for Neelam’s private ApplyIQ workspace.</p>{!ready&&<div className="analysis-banner">Verifying your invitation… If this remains visible, open the newest invitation email.</div>}<form className="form" onSubmit={submit}><label className="field">New password<input className="input" name="password" type="password" autoComplete="new-password" required minLength={12}/></label><label className="field">Confirm password<input className="input" name="confirmation" type="password" autoComplete="new-password" required minLength={12}/></label>{message&&<div className="error-box" role="alert">{message}</div>}<button className="btn primary" disabled={!ready||pending}>{pending?"Saving securely…":"Create password"}</button></form></div></div>}
