import "server-only";
import { experiences as seedExperiences } from "@/lib/data";
import { isPreviewMode } from "@/lib/preview";
import { isSupabaseConfigured } from "@/lib/supabase/config";
import { createSupabaseServerClient, requireUser } from "@/lib/supabase/server";
export type CareerEvidence={id:string;employer:string;position:string;period:string;type:string;content:string;tags:string[];verified:boolean;sourceReference:string|null};
export async function listCareerEvidence():Promise<CareerEvidence[]>{if(!isSupabaseConfigured()||await isPreviewMode())return seedExperiences.map(item=>({id:item.id,employer:item.employer,position:item.position,period:item.period,type:item.type,content:item.text,tags:item.tags,verified:item.verified,sourceReference:"Master résumé"}));const supabase=await createSupabaseServerClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return [];const {data,error}=await supabase.from("career_experiences").select("id,experience_type,content,source_reference,verified,metadata,career_positions(employer,title,start_date,end_date)").order("created_at");if(error){console.error("Could not list Career Truth",error);return []}return (data??[]).map(row=>{const position=Array.isArray(row.career_positions)?row.career_positions[0]:row.career_positions;return {id:row.id,employer:position?.employer||"Employer",position:position?.title||"Position",period:[position?.start_date,position?.end_date].filter(Boolean).join(" – ")||"Dates not recorded",type:row.experience_type,content:row.content,tags:Array.isArray(row.metadata?.tags)?row.metadata.tags.filter((tag:unknown):tag is string=>typeof tag==="string"):[],verified:row.verified,sourceReference:row.source_reference}})}
export async function createCareerEvidence(input:{employer:string;position:string;type:string;content:string;tags:string[];sourceReference?:string}){if(await isPreviewMode())return {id:crypto.randomUUID(),preview:true};const {supabase,user}=await requireUser();const {data:profile}=await supabase.from("profiles").select("id").eq("auth_user_id",user.id).single();if(!profile)throw new Error("Private profile not found");let {data:position}=await supabase.from("career_positions").select("id").eq("profile_id",profile.id).eq("employer",input.employer).eq("title",input.position).maybeSingle();if(!position){const result=await supabase.from("career_positions").insert({profile_id:profile.id,employer:input.employer,title:input.position}).select("id").single();if(result.error)throw result.error;position=result.data}const {data,error}=await supabase.from("career_experiences").insert({position_id:position.id,experience_type:input.type,content:input.content,source_reference:input.sourceReference||"User-confirmed manual entry",verified:true,metadata:{tags:input.tags}}).select("id").single();if(error)throw error;return {id:data.id as string,preview:false}}
export async function updateCareerEvidence(id:string,input:{content:string;verified:boolean;tags:string[]}){if(await isPreviewMode())return {preview:true};const {supabase}=await requireUser();const {error}=await supabase.from("career_experiences").update({content:input.content,verified:input.verified,metadata:{tags:input.tags},updated_at:new Date().toISOString()}).eq("id",id);if(error)throw error;return {preview:false}}
export async function getCareerBreakLanguage(){if(await isPreviewMode())return "";const supabase=await createSupabaseServerClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return "";const {data}=await supabase.from("profiles").select("approved_career_break_language").eq("auth_user_id",user.id).single();return data?.approved_career_break_language||""}
export async function saveCareerBreakLanguage(language:string){if(await isPreviewMode())return {preview:true};const {supabase,user}=await requireUser();const {error}=await supabase.from("profiles").update({approved_career_break_language:language||null,updated_at:new Date().toISOString()}).eq("auth_user_id",user.id);if(error)throw error;return {preview:false}}
