import "server-only";
import { isPreviewMode } from "@/lib/preview";
import { isSupabaseConfigured } from "@/lib/supabase/config";
import { createSupabaseServerClient, requireUser } from "@/lib/supabase/server";
import { getJob } from "@/lib/repositories/jobs";
import type { Job } from "@/lib/types";
export type InterviewRecord={id:string;jobId:string;company:string;role:string;type:string;startsAt:string;interviewer:string|null;interviewerTitle:string|null;stage:string|null;notes:string|null;outcome:string|null};
const previewInterview:InterviewRecord={id:"preview-arc-screen",jobId:"arc-events",company:"Arcwell Foundation",role:"Events & Engagement Lead",type:"Video",startsAt:"2026-08-25T10:30:00-04:00",interviewer:"Jordan Lee",interviewerTitle:"Talent Partner",stage:"Recruiter Screen",notes:null,outcome:null};
export async function listInterviews():Promise<InterviewRecord[]>{if(!isSupabaseConfigured()||await isPreviewMode())return [previewInterview];const supabase=await createSupabaseServerClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return [];const {data,error}=await supabase.from("interviews").select("id,interview_type,starts_at,interviewer,interviewer_title,stage,notes,outcome,applications(job_id,jobs(title,companies(name)))").order("starts_at");if(error){console.error("Could not list interviews",error);return []}return (data??[]).map(row=>{const application=Array.isArray(row.applications)?row.applications[0]:row.applications;const job=Array.isArray(application?.jobs)?application.jobs[0]:application?.jobs;const company=Array.isArray(job?.companies)?job.companies[0]:job?.companies;return {id:row.id,jobId:application?.job_id||"",company:company?.name||"Company",role:job?.title||"Role",type:row.interview_type,startsAt:row.starts_at,interviewer:row.interviewer,interviewerTitle:row.interviewer_title,stage:row.stage,notes:row.notes,outcome:row.outcome}})}
export async function createInterview(input:{jobId:string;type:string;startsAt:string;interviewer?:string;interviewerTitle?:string;stage?:string;notes?:string}){if(await isPreviewMode())return {id:crypto.randomUUID(),preview:true};const {supabase,user}=await requireUser();const {data:profile}=await supabase.from("profiles").select("id").eq("auth_user_id",user.id).single();if(!profile)throw new Error("Private profile not found");const {data:application}=await supabase.from("applications").select("id").eq("profile_id",profile.id).eq("job_id",input.jobId).single();if(!application)throw new Error("Start an application before adding an interview");const {data,error}=await supabase.from("interviews").insert({application_id:application.id,interview_type:input.type,starts_at:input.startsAt,interviewer:input.interviewer||null,interviewer_title:input.interviewerTitle||null,stage:input.stage||null,notes:input.notes||null}).select("id").single();if(error)throw error;return {id:data.id as string,preview:false}}
export async function getInterview(id:string):Promise<{interview:InterviewRecord;job:Job}|null>{if(await isPreviewMode()){if(id!==previewInterview.id)return null;const job=await getJob(previewInterview.jobId);return job?{interview:previewInterview,job}:null}const interviews=await listInterviews();const interview=interviews.find(item=>item.id===id);if(!interview)return null;const job=await getJob(interview.jobId);return job?{interview,job}:null}
export async function updateInterviewOutcome(id:string,input:{outcome:string;notes:string}){if(await isPreviewMode())return {preview:true};const {supabase}=await requireUser();const {error}=await supabase.from("interviews").update({outcome:input.outcome||null,notes:input.notes||null}).eq("id",id);if(error)throw error;return {preview:false}}
