import "server-only";
import { isPreviewMode } from "@/lib/preview";
import { isSupabaseConfigured } from "@/lib/supabase/config";
import { createSupabaseServerClient, requireUser } from "@/lib/supabase/server";
import { discoverAtsJobs, type DiscoveredJob } from "@/lib/job-discovery/ats";
import { prioritizeDiscoveredJobs } from "@/lib/job-discovery/prioritize";

export type JobFeed={id:string;name:string;boardUrl:string;provider:string;active:boolean;lastCheckedAt:string|null;lastJobCount:number};
const previewFeeds:JobFeed[]=[{id:"preview-openai",name:"Example Ashby feed",boardUrl:"https://jobs.ashbyhq.com/openai",provider:"Ashby",active:true,lastCheckedAt:null,lastJobCount:0}];
export async function listJobFeeds():Promise<JobFeed[]>{if(!isSupabaseConfigured()||await isPreviewMode())return previewFeeds;const supabase=await createSupabaseServerClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return [];const {data,error}=await supabase.from("job_feeds").select("id,name,board_url,provider,active,last_checked_at,last_job_count").order("created_at");if(error){console.error("Could not list job feeds",error);return []}return (data??[]).map(row=>({id:row.id,name:row.name,boardUrl:row.board_url,provider:row.provider,active:row.active,lastCheckedAt:row.last_checked_at,lastJobCount:row.last_job_count}));}
function providerFromUrl(value:string){const host=new URL(value).hostname;if(host.includes("greenhouse.io"))return "Greenhouse";if(host.includes("lever.co"))return "Lever";if(host.includes("ashbyhq.com"))return "Ashby";throw new Error("Unsupported careers provider")}
export async function createJobFeed(input:{name:string;boardUrl:string}){if(await isPreviewMode())return {id:crypto.randomUUID(),provider:providerFromUrl(input.boardUrl),preview:true};const {supabase,user}=await requireUser();const {data:profile}=await supabase.from("profiles").select("id").eq("auth_user_id",user.id).single();if(!profile)throw new Error("Private profile not found");const provider=providerFromUrl(input.boardUrl);const {data,error}=await supabase.from("job_feeds").upsert({profile_id:profile.id,name:input.name,board_url:input.boardUrl,provider},{onConflict:"profile_id,board_url"}).select("id").single();if(error)throw error;return {id:data.id as string,provider,preview:false};}
export async function refreshJobFeeds():Promise<{feeds:number;jobs:number;scanned:number;results:Array<{feedId:string;jobs:DiscoveredJob[]}>}>{const feeds=await listJobFeeds();const results=[] as Array<{feedId:string;jobs:DiscoveredJob[]}>;let count=0;let scanned=0;for(const feed of feeds.filter(item=>item.active)){try{const allJobs=await discoverAtsJobs(feed.boardUrl);const jobs=prioritizeDiscoveredJobs(allJobs);scanned+=allJobs.length;count+=jobs.length;results.push({feedId:feed.id,jobs});if(!(await isPreviewMode())){const supabase=await createSupabaseServerClient();await supabase.from("job_feeds").update({last_checked_at:new Date().toISOString(),last_job_count:jobs.length,last_snapshot:jobs}).eq("id",feed.id)}}catch(error){console.error("Feed refresh failed",{feed:feed.id,error})}}return {feeds:results.length,jobs:count,scanned,results};}
