import type { DiscoveredJob } from "@/lib/job-discovery/ats";
const roleSignals=["learning","training","engagement","community","program","project","partnership","stakeholder","events","education","enablement","people","talent","operations","customer success"];
const strongRoleSignals=["learning","training","engagement","community","partnership","stakeholder","events","education","enablement","people","talent","customer success"];
const targetLocations=["new york","nyc","jersey city","new jersey","remote","united states","us -"];
const technicalTitle=/\b(machine learning|artificial intelligence|software|engineer(?:ing)?|data scien(?:ce|tist)|developer|cloud|cyber|security|infrastructure|solutions architect|technical program|product manager)\b/i;
function locationMatches(location:string,locations:string[]){const targets=locations.filter(value=>!value.includes("remote"));if(targets.some(target=>location.includes(target)))return true;const wantsRemote=locations.some(value=>value.includes("remote"));if(!wantsRemote)return false;const remote=location.includes("remote");const explicitlyForeign=/\b(india|canada|uk|united kingdom|europe|brussels|london|paris|germany|france|singapore|australia)\b/.test(location);return remote&&!explicitlyForeign&&(location==="remote"||/\b(us|usa|united states)\b/.test(location));}
export function assessDiscoveredJob(job:DiscoveredJob,preferences?:{roles?:string[];locations?:string[]}){const title=job.title.toLowerCase();const location=job.location.toLowerCase();const roles=preferences?.roles?.length?preferences.roles.map(x=>x.toLowerCase()):roleSignals;const locations=preferences?.locations?.length?preferences.locations.map(x=>x.toLowerCase()):targetLocations;const preferenceHits=roles.filter(signal=>title.includes(signal));const strongHits=strongRoleSignals.filter(signal=>title.includes(signal));const genericProgramFit=/\b(program|project|operations)\b/.test(title)&&!technicalTitle.test(title);const roleFit=strongHits.length>0||genericProgramFit;const locationFit=locationMatches(location,locations);const excessiveSeniority=/\b(chief|vice president|vp|head of)\b/.test(title);const technicalMismatch=technicalTitle.test(title);const score=Math.max(0,Math.min(100,strongHits.length*25+preferenceHits.length*15+(genericProgramFit?20:0)+(locationFit?30:0)-(excessiveSeniority?25:0)-(technicalMismatch?100:0)));const focus=strongHits.slice(0,2).join(" and ")||"non-technical program delivery";return {score,eligible:roleFit&&locationFit&&!technicalMismatch&&!excessiveSeniority,reason:`Matches Neelam’s ${focus} focus and ${job.location} preference.`};}
export function discoveryPriority(job:DiscoveredJob,preferences?:{roles?:string[];locations?:string[]}){return assessDiscoveredJob(job,preferences).score}
export function prioritizeDiscoveredJobs(jobs:DiscoveredJob[],limit=50,preferences?:{roles?:string[];locations?:string[]}){return jobs.map(job=>({job,assessment:assessDiscoveredJob(job,preferences)})).filter(item=>item.assessment.eligible&&item.assessment.score>=60).sort((a,b)=>b.assessment.score-a.assessment.score||((b.job.postedAt?Date.parse(b.job.postedAt):0)-(a.job.postedAt?Date.parse(a.job.postedAt):0))).slice(0,limit).map(({job,assessment})=>({...job,matchScore:assessment.score,matchReason:assessment.reason}))}
