"use client";
import { useState } from "react";
import { ArrowUpRight, RefreshCw, Rss, Search } from "lucide-react";
import type { DiscoveredJob } from "@/lib/job-discovery/ats";
import type { JobFeed } from "@/lib/repositories/job-feeds";

export function JobDiscovery({initialFeeds}:{initialFeeds:JobFeed[]}){const [jobs,setJobs]=useState<DiscoveredJob[]>([]);const [feeds,setFeeds]=useState(initialFeeds);const [lastSearch,setLastSearch]=useState<{name:string;boardUrl:string}|null>(null);const [error,setError]=useState("");const [message,setMessage]=useState("");const [pending,setPending]=useState(false);const [advanced,setAdvanced]=useState(false);
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setPending(true);setError("");setMessage("");setJobs([]);const values=Object.fromEntries(new FormData(event.currentTarget));const boardUrl=String(values.boardUrl||"");const name=String(values.name||"");const response=await fetch("/api/jobs/discover",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({boardUrl,companyName:name})});const result=await response.json() as {jobs?:DiscoveredJob[];boardUrl?:string;scanned?:number;error?:string};if(!response.ok){setError(result.error||"Could not find that company’s careers board.");setPending(false);return;}setLastSearch({name,boardUrl:result.boardUrl||boardUrl});setJobs(result.jobs||[]);setMessage(`Found ${result.scanned||0} live vacancies and selected ${result.jobs?.length||0} that match your preferences.`);setPending(false);}
  async function saveFeed(){if(!lastSearch)return;setPending(true);setError("");const response=await fetch("/api/job-feeds",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(lastSearch)});const result=await response.json() as {id?:string;provider?:string;error?:string};if(!response.ok){setError(result.error||"Could not save this feed.");setPending(false);return}setFeeds(current=>current.some(feed=>feed.boardUrl===lastSearch.boardUrl)?current:[...current,{id:result.id!,name:lastSearch.name,boardUrl:lastSearch.boardUrl,provider:result.provider!,active:true,lastCheckedAt:new Date().toISOString(),lastJobCount:jobs.length}]);setMessage("Company feed saved. It is ready for scheduled refreshes.");setPending(false)}
  async function refreshAll(){setPending(true);setError("");setMessage("");const response=await fetch("/api/discovery/run",{method:"POST"});const result=await response.json() as {feeds?:number;jobs?:number;scanned?:number;results?:Array<{jobs:DiscoveredJob[]}>;error?:string};if(!response.ok){setError(result.error||"Could not refresh feeds.");setPending(false);return}const unique=new Map<string,DiscoveredJob>();for(const job of result.results?.flatMap(item=>item.jobs)||[])unique.set(`${job.provider}:${job.externalId}`,job);setJobs([...unique.values()].sort((a,b)=>(b.postedAt?Date.parse(b.postedAt):0)-(a.postedAt?Date.parse(a.postedAt):0)));setMessage(`Scanned ${result.scanned||0} published jobs across ${result.feeds||0} feeds and shortlisted ${result.jobs||0} relevant candidates.`);setPending(false)}
  return <div className="stack"><section className="card"><div className="section-head"><div><h2>Monitored companies</h2><p className="subtle">Saved feeds can be refreshed together now and scheduled after deployment.</p></div><button className="btn" onClick={refreshAll} disabled={pending||!feeds.length}><RefreshCw size={14}/>Refresh all</button></div><div className="feed-list">{feeds.map(feed=><div className="feed-chip" key={feed.id}><Rss size={14}/><span><strong>{feed.name}</strong><small>{feed.provider} · {feed.lastJobCount} last found</small></span></div>)}{!feeds.length&&<p className="subtle">No monitored company feeds yet.</p>}</div></section><section className="card company-search-card"><form className="form" onSubmit={submit}><label className="field">Company name<input className="input company-name-input" name="name" placeholder="e.g. OpenAI, Spotify or JPMorgan" required autoComplete="organization"/></label><p className="subtle">ApplyIQ will locate the company’s public Greenhouse, Lever or Ashby board and return roles matching your saved preferences.</p>{advanced&&<label className="field advanced-board">Careers board URL <span className="subtle">(optional override)</span><input className="input" name="boardUrl" type="url" placeholder="https://jobs.ashbyhq.com/company"/></label>}{error&&<div className="error-box" role="alert">{error}</div>}{message&&<div className="analysis-banner">{message}</div>}<div className="actions"><button className="btn primary" disabled={pending}><Search size={15}/>{pending?"Finding the company and roles…":"Find matching roles"}</button><button className="btn" type="button" onClick={()=>setAdvanced(value=>!value)}>{advanced?"Hide advanced":"Advanced: use careers URL"}</button></div></form></section>{jobs.length>0&&<section><div className="section-head"><div><h2>{jobs.length} matching vacancies</h2><p className="subtle">Filtered using the roles and locations saved in Settings</p></div>{lastSearch&&!feeds.some(feed=>feed.boardUrl===lastSearch.boardUrl)&&<button className="btn" onClick={saveFeed} disabled={pending}><Rss size={14}/>Monitor this company</button>}</div><div className="stack" style={{gap:10}}>{jobs.map(job=><article className="card opportunity" key={`${job.provider}-${job.externalId}`}><div><h3>{job.title}</h3><div className="job-company">{job.location} · {job.provider}</div><div className="job-meta"><span>{job.postedAt?`Updated ${new Date(job.postedAt).toLocaleDateString()}`:"Publishing date unavailable"}</span></div></div><div className="actions"><a className="btn primary" href={`/jobs/new?url=${encodeURIComponent(job.jobUrl)}`}>Analyze match</a><a className="btn" href={job.jobUrl} target="_blank" rel="noreferrer">View posting <ArrowUpRight size={14}/></a></div></article>)}</div></section>}</div>;
}
