"use client";
import { useState } from "react";
import { Save } from "lucide-react";
import type { JobPreferences } from "@/lib/repositories/preferences";
const split=(value:string)=>value.split(",").map(x=>x.trim()).filter(Boolean);

export function JobPreferencesSettings({initial}:{initial:JobPreferences}){
  const [pending,setPending]=useState(false);const [message,setMessage]=useState("");const [error,setError]=useState("");
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setPending(true);setError("");setMessage("");const data=new FormData(event.currentTarget);const payload={roles:split(String(data.get("roles")||"")),locations:split(String(data.get("locations")||"")),excludedRoles:split(String(data.get("excludedRoles")||"")),excludedIndustries:split(String(data.get("excludedIndustries")||"")),arrangements:data.getAll("arrangements").map(String),employmentTypes:data.getAll("employmentTypes").map(String),minimumSalary:Number(data.get("minimumSalary"))};const response=await fetch("/api/settings/job-preferences",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const result=await response.json() as {error?:string;preview?:boolean};if(response.ok)setMessage(result.preview?"Preferences applied to this demo view.":"Preferences saved. Future searches and daily recommendations will use them.");else setError(result.error||"Preferences could not be saved.");setPending(false)}
  return <section className="card"><div className="section-head"><div><h2>Job preferences</h2><p className="subtle">These rules filter company searches and explain each recommendation.</p></div></div><form className="form" onSubmit={submit}><label className="field">Target roles and keywords<input className="input" name="roles" defaultValue={initial.roles.join(", ")} placeholder="Learning, Program, Engagement"/><span className="field-help">Separate multiple preferences with commas.</span></label><label className="field">Target locations<input className="input" name="locations" defaultValue={initial.locations.join(", ")} placeholder="New York, New Jersey, Remote"/></label><div className="grid two-col"><label className="field">Roles to exclude<input className="input" name="excludedRoles" defaultValue={initial.excludedRoles.join(", ")} placeholder="Machine Learning, Technical Program"/></label><label className="field">Industries to exclude<input className="input" name="excludedIndustries" defaultValue={initial.excludedIndustries.join(", ")} placeholder="Add only if needed"/></label></div><label className="field">Minimum annual salary<input className="input" name="minimumSalary" type="number" min="0" step="1000" defaultValue={initial.minimumSalary}/></label><fieldset className="preference-group"><legend>Work arrangement</legend>{["Remote","Hybrid","On-site"].map(value=><label className="check-field" key={value}><input type="checkbox" name="arrangements" value={value} defaultChecked={initial.arrangements.includes(value)}/>{value}</label>)}</fieldset><fieldset className="preference-group"><legend>Employment type</legend>{["Full-time","Part-time","Contract"].map(value=><label className="check-field" key={value}><input type="checkbox" name="employmentTypes" value={value} defaultChecked={initial.employmentTypes.includes(value)}/>{value}</label>)}</fieldset>{error&&<div className="error-box" role="alert">{error}</div>}{message&&<div className="analysis-banner">{message}</div>}<button className="btn primary" disabled={pending}><Save size={14}/>{pending?"Saving…":"Save preferences"}</button></form></section>;
}
