"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { ArrowRight, BookmarkPlus, RotateCcw, X } from "lucide-react";
import type { CompleteJobAnalysis } from "@/lib/ai/job-analysis";
import { CategoryPill } from "@/components/ui";

type Result = { analysis: CompleteJobAnalysis; persisted: boolean; id: string | null; extractionMethod: "json-ld" | "html" | "manual" };
export function JobIntakeForm({initialUrl=""}:{initialUrl?:string}) {
  const router=useRouter();
  const [pending,setPending]=useState(false); const [error,setError]=useState(""); const [result,setResult]=useState<Result|null>(null); const [manual,setManual]=useState(false);
  const [decisionPending,setDecisionPending]=useState<"shortlist"|"apply"|"reject"|null>(null); const [confirmReject,setConfirmReject]=useState(false);
  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setPending(true); setError(""); setResult(null);
    const data = Object.fromEntries(new FormData(event.currentTarget));
    try { const response=await fetch("/api/jobs/analyze",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)}); const body=await response.json(); if(!response.ok) throw new Error(body.error); setResult(body); }
    catch(e){setError(e instanceof Error?e.message:"Analysis failed");} finally {setPending(false);}
  }
  async function decide(action:"shortlist"|"apply"|"reject") {
    if(!result?.id){if(action==="reject")setResult(null);else setError("Sign in to save this analysis to your job list.");return;}
    if(action==="reject"&&!confirmReject){setConfirmReject(true);return;}
    setDecisionPending(action);setError("");
    try {
      const response=action==="reject"
        ? await fetch(`/api/jobs/${result.id}/feedback`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({feedbackType:"dismissed",reason:"Not pursuing",notes:"Dismissed after URL analysis"})})
        : await fetch(`/api/applications/${result.id}/stage`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({stage:action==="apply"?"Preparing Application":"Shortlisted"})});
      if(!response.ok)throw new Error((await response.json().catch(()=>null) as {error?:string}|null)?.error||"The decision could not be saved.");
      router.push(action==="apply"?`/jobs/${result.id}/studio`:action==="shortlist"?`/jobs/${result.id}`:"/jobs");router.refresh();
    } catch(e){setError(e instanceof Error?e.message:"The decision could not be saved.");setDecisionPending(null);}
  }
  return <div className="stack" style={{maxWidth:900}}><div className="card"><form className="form" onSubmit={submit}><div className="url-hero"><label className="field">Job posting URL<input className="input url-input" name="sourceUrl" type="url" placeholder="https://company.com/careers/job…" defaultValue={initialUrl} required/></label><p className="subtle">ApplyIQ reads the public page, extracts the role, and checks it against verified Career Truth. Nothing is submitted to the employer.</p></div>{manual&&<div className="manual-fields"><div className="analysis-banner">Manual recovery overrides page extraction. Complete every field.</div><label className="field">Job title<input className="input" name="title" placeholder="e.g. Learning Program Manager" minLength={2} required={manual}/></label><div className="grid" style={{gridTemplateColumns:"1fr 1fr"}}><label className="field">Company<input className="input" name="company" placeholder="Company name" required={manual}/></label><label className="field">Location<input className="input" name="location" placeholder="New York, NY" required={manual}/></label></div><label className="field">Job description<textarea className="input" name="description" placeholder="Paste the complete description…" minLength={100} required={manual}/></label></div>}{error&&<div className="error-box" role="alert">{error}</div>}<div className="actions"><button className="btn primary" disabled={pending}>{pending?"Reading and analyzing…":"Analyze job URL"}</button><button className="btn" type="button" onClick={()=>setManual(v=>!v)}>{manual?"Hide manual recovery":"Page blocked? Enter details manually"}</button></div></form></div>{result&&<AnalysisPreview result={result} pending={decisionPending} confirmReject={confirmReject} onDecision={decide} onReset={()=>{setResult(null);setConfirmReject(false)}}/>}</div>;
}
function AnalysisPreview({result,pending,confirmReject,onDecision,onReset}:{result:Result;pending:"shortlist"|"apply"|"reject"|null;confirmReject:boolean;onDecision:(action:"shortlist"|"apply"|"reject")=>void;onReset:()=>void}) { const a=result.analysis; return <section className="card"><div className="section-head"><div><div className="eyebrow">Analysis complete · {result.extractionMethod === "json-ld" ? "Structured job data" : result.extractionMethod === "html" ? "Public page content" : "Manual recovery"} · {a.provider === "openai" ? "OpenAI" : "Explainable scoring"}</div><h2>{a.title} · {a.company}</h2></div><div className="score"><strong>{a.score}</strong><CategoryPill category={a.category}/></div></div><div className="analysis-banner">{result.persisted?"Imported as a new opportunity. Choose what you want to do next.":"Preview analysis only. Sign in to save this opportunity."}</div><p>{a.summary}</p><div className="grid two-col"><div><h3>Strongest evidence</h3><ul className="list">{a.strengths.length?a.strengths.map(x=><li key={x}>{x}</li>):<li>No strong evidence identified.</li>}</ul></div><div><h3>Gaps</h3><ul className="list">{a.gaps.length?a.gaps.map(x=><li key={x}>{x}</li>):<li>No material gaps identified.</li>}</ul></div></div><div className="section"><h3>Requirements matrix</h3><div className="table-wrap"><table><thead><tr><th>Requirement</th><th>Importance</th><th>Evidence</th><th>Strength</th></tr></thead><tbody>{a.requirements.map(r=><tr key={r.requirement}><td>{r.requirement}</td><td>{r.importance}</td><td>{r.evidence}</td><td>{r.strength}</td></tr>)}</tbody></table></div></div><div className="decision-panel"><div><div className="eyebrow">Your decision</div><h3>What would you like to do with this role?</h3></div><div className="decision-actions"><button className="btn" disabled={Boolean(pending)} onClick={()=>onDecision("shortlist")}><BookmarkPlus size={14}/>{pending==="shortlist"?"Saving…":"Add to shortlist"}</button><button className="btn primary" disabled={Boolean(pending)} onClick={()=>onDecision("apply")}>{pending==="apply"?"Opening Studio…":"Continue application"}<ArrowRight size={14}/></button><button className="btn danger" disabled={Boolean(pending)} onClick={()=>onDecision("reject")}><X size={14}/>{pending==="reject"?"Rejecting…":confirmReject?"Confirm reject":"Reject role"}</button><button className="btn quiet-btn" disabled={Boolean(pending)} onClick={onReset}><RotateCcw size={14}/>Analyze another</button></div></div></section> }
