"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { ExternalLink, Search, Trash2 } from "lucide-react";
import type { ApplicationStage, Job } from "@/lib/types";
import { CategoryPill } from "@/components/ui";

const stages:Array<{label:string;value:ApplicationStage}>=[{label:"Discovered",value:"Discovered"},{label:"Shortlisted",value:"Shortlisted"},{label:"Applied",value:"Applied"},{label:"Interview",value:"Interview"},{label:"Offered",value:"Offer"},{label:"Rejected",value:"Rejected"}];
const visibleStage=(stage:ApplicationStage):ApplicationStage=>stage==="Preparing Application"||stage==="Ready to Apply"?"Shortlisted":stage==="Recruiter Screen"||stage==="Final Interview"?"Interview":stage==="Withdrawn"||stage==="Closed"?"Rejected":stage;
function nextAction(job:Job){const stage=visibleStage(job.status);if(stage==="Discovered")return {label:"Review fit",href:`/jobs/${job.id}`};if(stage==="Shortlisted")return {label:"Prepare",href:`/jobs/${job.id}/studio`};if(stage==="Applied")return {label:"Outreach",href:`/contacts?job=${job.id}`};if(stage==="Interview")return {label:"Interview prep",href:"/interviews"};return {label:"View",href:`/jobs/${job.id}`}}
export function JobsTable({initialJobs}:{initialJobs:Job[]}){
  const [jobs,setJobs]=useState(initialJobs);const [query,setQuery]=useState("");const [pending,setPending]=useState("");
  const visible=useMemo(()=>jobs.filter(job=>`${job.title} ${job.company} ${job.location}`.toLowerCase().includes(query.toLowerCase())),[jobs,query]);
  async function updateStage(job:Job,stage:ApplicationStage){setPending(job.id);const response=await fetch(`/api/applications/${job.id}/stage`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({stage})});if(response.ok)setJobs(current=>current.map(item=>item.id===job.id?{...item,status:stage}:item));setPending("")}
  async function remove(job:Job){if(!window.confirm(`Remove ${job.title} at ${job.company} from the jobs table?`))return;setPending(job.id);const response=await fetch(`/api/jobs/${job.id}`,{method:"DELETE"});if(response.ok)setJobs(current=>current.filter(item=>item.id!==job.id));setPending("")}
  return <><label className="job-table-search"><Search size={15}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search title, company or location" aria-label="Search jobs"/></label>{visible.length?<div className="card table-wrap jobs-master-table"><table><thead><tr><th>Job</th><th>Match</th><th>Location</th><th>Stage</th><th>Next action</th></tr></thead><tbody>{visible.map(job=>{const action=nextAction(job);return <tr key={job.id}><td><Link href={`/jobs/${job.id}`}><strong>{job.title}</strong><small>{job.company} · {job.salary??"Salary not listed"}</small></Link></td><td><strong className="job-score">{job.score}</strong><CategoryPill category={job.category}/></td><td>{job.location}<small>{job.arrangement}</small></td><td><select className="compact-select" value={visibleStage(job.status)} disabled={pending===job.id} onChange={event=>updateStage(job,event.target.value as ApplicationStage)}>{stages.map(stage=><option key={stage.value} value={stage.value}>{stage.label}</option>)}</select></td><td><div className="compact-actions"><Link className="mini-btn primary-mini" href={action.href}><ExternalLink size={13}/>{action.label}</Link><button className="mini-btn danger" type="button" aria-label={`Remove ${job.title}`} title="Remove job" disabled={pending===job.id} onClick={()=>remove(job)}><Trash2 size={13}/></button></div></td></tr>})}</tbody></table></div>:<div className="card empty"><h2>No jobs yet</h2><p className="subtle">Add a job URL to begin Neelam’s private jobs table.</p><Link className="btn primary" href="/jobs/discover">Add first job</Link></div>}</>;
}
