"use client";

import { useState } from "react";
import { ArrowDown, ArrowUpRight, CheckCircle2, Download, FileQuestion, FileText, Send } from "lucide-react";
import type { ApplicationStudio } from "@/lib/application-studio";
import { ChangeReview } from "@/components/change-review";

type JobContext={id:string;title:string;company:string;sourceUrl?:string};

export function StudioWorkflow({job,studio}:{job:JobContext;studio:ApplicationStudio}){const [accepted,setAccepted]=useState<Record<string,string>>({});const [status,setStatus]=useState("");const [downloading,setDownloading]=useState(false);const acceptedItems=studio.changes.filter(change=>accepted[change.id]);function decide(id:string,value:string|null|undefined){setAccepted(current=>{const next={...current};if(value)next[id]=value;else delete next[id];return next})}async function downloadResume(){setDownloading(true);setStatus("");try{const response=await fetch(`/api/applications/studio/${job.id}/resume`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({acceptedChanges:accepted})});if(!response.ok)throw new Error("PDF generation failed");const url=URL.createObjectURL(await response.blob());const link=document.createElement("a");link.href=url;link.download=`${job.company.replace(/[^a-z0-9]+/gi,"-").toLowerCase()}-tailored-resume.pdf`;link.click();URL.revokeObjectURL(url);setStatus("Full tailored résumé downloaded as a PDF.")}catch{setStatus("Could not generate the PDF résumé. Please try again.")}finally{setDownloading(false)}}async function markApplied(){setStatus("Saving…");const response=await fetch(`/api/applications/${job.id}/stage`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({stage:"Applied"})});setStatus(response.ok?"Marked as applied. Your pipeline and follow-up workflow are updated.":"Could not update the application status.")}
  return <><section className="section"><div className="section-head"><div><h2>1. Review résumé adjustments</h2><p className="subtle">Accept, edit or reject every change. Accepted wording appears in the tailored résumé below.</p></div><span className="pill">{acceptedItems.length} accepted</span></div><div className="stack">{studio.changes.map(change=><ChangeReview change={change} key={change.id} onDecision={value=>decide(change.id,value)}/>)}</div></section><section className="section card tailored-resume" id="tailored-resume"><div className="section-head"><div><div className="eyebrow">Your updated résumé</div><h2>Full tailored résumé preview</h2></div><button className="btn primary" type="button" disabled={downloading} onClick={downloadResume}><Download size={14}/>{downloading?"Creating PDF…":"Download full résumé PDF"}</button></div><p className="resume-summary">{studio.summary}</p><div className="tags">{studio.skills.map(skill=><span className="tag" key={skill}>{skill}</span>)}</div><h3>Tailored highlights</h3>{acceptedItems.length?<ul className="resume-bullets">{acceptedItems.map(change=><li key={change.id}>{accepted[change.id]}</li>)}</ul>:<div className="analysis-banner">Accept résumé adjustments above and they will appear in the PDF. The download always includes the complete verified employment history.</div>}</section><section className="section card continuation-panel"><div><div className="eyebrow">Continue your application</div><h2>Your next steps</h2><p className="subtle">Move through these in order, then submit on the employer’s website.</p></div><div className="continuation-actions"><a className="application-step" href="#cover-letter"><span>2</span><FileText size={18}/><strong>Review cover letter</strong><ArrowDown size={14}/></a><a className="application-step" href="#application-questions"><span>3</span><FileQuestion size={18}/><strong>Answer questions</strong><ArrowDown size={14}/></a><button className="application-step" type="button" disabled={downloading} onClick={downloadResume}><span>4</span><Download size={18}/><strong>{downloading?"Creating PDF…":"Download full PDF"}</strong></button>{job.sourceUrl?<a className="application-step primary-step" href={job.sourceUrl} target="_blank" rel="noreferrer"><span>5</span><ArrowUpRight size={18}/><strong>Open employer application</strong></a>:<span className="application-step disabled-step"><span>5</span><ArrowUpRight size={18}/><strong>Original posting unavailable</strong></span>}<button className="application-step" type="button" onClick={markApplied}><span>6</span><Send size={18}/><strong>Mark as applied</strong></button></div>{status?<div className={status.includes("downloaded")||status.startsWith("Marked")?"analysis-banner":"error-box"}><CheckCircle2 size={14}/> {status}</div>:null}</section></>;
}
