"use client";

import { useState } from "react";
import { ArrowDown, ArrowUpRight, CheckCircle2, Download, FileQuestion, FileText, Send } from "lucide-react";
import type { ApplicationStudio } from "@/lib/application-studio";
import { ChangeReview } from "@/components/change-review";

type JobContext={id:string;title:string;company:string;sourceUrl?:string};
function escapeHtml(value:string){return value.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;")}

export function StudioWorkflow({job,studio}:{job:JobContext;studio:ApplicationStudio}){const [accepted,setAccepted]=useState<Record<string,string>>({});const [status,setStatus]=useState("");const acceptedItems=studio.changes.filter(change=>accepted[change.id]);function decide(id:string,value:string|null|undefined){setAccepted(current=>{const next={...current};if(value)next[id]=value;else delete next[id];return next})}function downloadResume(){const bullets=acceptedItems.length?acceptedItems.map(change=>accepted[change.id]):studio.changes.map(change=>change.tailored);const html=`<!doctype html><html><head><meta charset="utf-8"><title>Neelam Jagait — ${escapeHtml(job.company)}</title><style>body{font:11pt Arial;line-height:1.5;max-width:760px;margin:42px auto;color:#17211f}h1{margin-bottom:2px}h2{margin-top:26px;border-bottom:1px solid #bbb;padding-bottom:5px}.meta{color:#60706b}li{margin:8px 0}</style></head><body><h1>Neelam Jagait</h1><p class="meta">Tailored résumé · ${escapeHtml(job.title)} · ${escapeHtml(job.company)}</p><h2>Professional summary</h2><p>${escapeHtml(studio.summary)}</p><h2>Core skills</h2><p>${studio.skills.map(escapeHtml).join(" · ")}</p><h2>Selected experience</h2><ul>${bullets.map(item=>`<li>${escapeHtml(item)}</li>`).join("")}</ul></body></html>`;const url=URL.createObjectURL(new Blob([html],{type:"text/html"}));const link=document.createElement("a");link.href=url;link.download=`${job.company.replace(/[^a-z0-9]+/gi,"-").toLowerCase()}-tailored-resume.html`;link.click();URL.revokeObjectURL(url)}async function markApplied(){setStatus("Saving…");const response=await fetch(`/api/applications/${job.id}/stage`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({stage:"Applied"})});setStatus(response.ok?"Marked as applied. Your pipeline and follow-up workflow are updated.":"Could not update the application status.")}
  return <><section className="section"><div className="section-head"><div><h2>1. Review résumé adjustments</h2><p className="subtle">Accept, edit or reject every change. Accepted wording appears in the tailored résumé below.</p></div><span className="pill">{acceptedItems.length} accepted</span></div><div className="stack">{studio.changes.map(change=><ChangeReview change={change} key={change.id} onDecision={value=>decide(change.id,value)}/>)}</div></section><section className="section card tailored-resume" id="tailored-resume"><div className="section-head"><div><div className="eyebrow">Your updated résumé</div><h2>Tailored résumé preview</h2></div><button className="btn primary" type="button" onClick={downloadResume}><Download size={14}/>Download tailored résumé</button></div><p className="resume-summary">{studio.summary}</p><div className="tags">{studio.skills.map(skill=><span className="tag" key={skill}>{skill}</span>)}</div><h3>Selected tailored experience</h3>{acceptedItems.length?<ul className="resume-bullets">{acceptedItems.map(change=><li key={change.id}>{accepted[change.id]}</li>)}</ul>:<div className="analysis-banner">Accept résumé adjustments above and they will appear here. Until then, the download uses ApplyIQ’s reviewed recommendations.</div>}</section><section className="section card continuation-panel"><div><div className="eyebrow">Continue your application</div><h2>Your next steps</h2><p className="subtle">Move through these in order, then submit on the employer’s website.</p></div><div className="continuation-actions"><a className="application-step" href="#cover-letter"><span>2</span><FileText size={18}/><strong>Review cover letter</strong><ArrowDown size={14}/></a><a className="application-step" href="#application-questions"><span>3</span><FileQuestion size={18}/><strong>Answer questions</strong><ArrowDown size={14}/></a><button className="application-step" type="button" onClick={downloadResume}><span>4</span><Download size={18}/><strong>Download résumé</strong></button>{job.sourceUrl?<a className="application-step primary-step" href={job.sourceUrl} target="_blank" rel="noreferrer"><span>5</span><ArrowUpRight size={18}/><strong>Open employer application</strong></a>:<span className="application-step disabled-step"><span>5</span><ArrowUpRight size={18}/><strong>Original posting unavailable</strong></span>}<button className="application-step" type="button" onClick={markApplied}><span>6</span><Send size={18}/><strong>Mark as applied</strong></button></div>{status&&<div className={status.startsWith("Marked")?"analysis-banner":"error-box"}><CheckCircle2 size={14}/> {status}</div>}</section></>;
}
