"use client";

import { useState } from "react";
import { ArrowDown, ArrowUpRight, CheckCircle2, Download, FileQuestion, FileText, Send } from "lucide-react";
import type { ApplicationStudio } from "@/lib/application-studio";
import { ChangeReview } from "@/components/change-review";

type JobContext={id:string;title:string;company:string;sourceUrl?:string};

export function StudioWorkflow({job,studio}:{job:JobContext;studio:ApplicationStudio}){const [accepted,setAccepted]=useState<Record<string,string>>({});const [status,setStatus]=useState("");const [downloading,setDownloading]=useState(false);const acceptedItems=studio.changes.filter(change=>accepted[change.id]);function decide(id:string,value:string|null|undefined){setAccepted(current=>{const next={...current};if(value)next[id]=value;else delete next[id];return next})}async function downloadResume(){setDownloading(true);setStatus("");try{const response=await fetch(`/api/applications/studio/${job.id}/resume`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({acceptedChanges:accepted})});if(!response.ok){const result=await response.json().catch(()=>null) as {error?:string}|null;throw new Error(result?.error||"Résumé generation failed")}const url=URL.createObjectURL(await response.blob());const link=document.createElement("a");link.href=url;link.download=`${job.company.replace(/[^a-z0-9]+/gi,"-").toLowerCase()}-tailored-resume.docx`;link.click();URL.revokeObjectURL(url);setStatus("Tailored résumé downloaded in the exact original Word format.")}catch(error){setStatus(error instanceof Error?error.message:"Could not generate the tailored résumé.")}finally{setDownloading(false)}}async function markApplied(){setStatus("Saving…");const response=await fetch(`/api/applications/${job.id}/stage`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({stage:"Applied"})});setStatus(response.ok?"Marked as applied. Your pipeline and follow-up workflow are updated.":"Could not update the application status.")}
  return <><section className="section"><div className="section-head"><div><h2>1. Review résumé adjustments</h2><p className="subtle">Accept, edit or reject every change. Only accepted wording is changed in the original résumé.</p></div><span className="pill">{acceptedItems.length} accepted</span></div><div className="stack">{studio.changes.map(change=><ChangeReview change={change} key={change.id} onDecision={value=>decide(change.id,value)}/>)}</div></section><section className="section card tailored-resume" id="tailored-resume"><div className="section-head"><div><div className="eyebrow">Original formatting preserved</div><h2>Tailored résumé wording</h2></div><button className="btn primary" type="button" disabled={downloading} onClick={downloadResume}><Download size={14}/>{downloading?"Preparing original…":"Download formatted Word résumé"}</button></div><p className="resume-summary">ApplyIQ uses Neelam’s uploaded master DOCX as the template. Fonts, spacing, sections, margins and page design remain unchanged.</p><h3>Accepted replacements</h3>{acceptedItems.length?<ul className="resume-bullets">{acceptedItems.map(change=><li key={change.id}>{accepted[change.id]}</li>)}</ul>:<div className="analysis-banner">Accept adjustments above before downloading. All other résumé content remains exactly as uploaded.</div>}</section><section className="section card continuation-panel"><div><div className="eyebrow">Continue your application</div><h2>Your next steps</h2><p className="subtle">Move through these in order, then submit on the employer’s website.</p></div><div className="continuation-actions"><a className="application-step" href="#cover-letter"><span>2</span><FileText size={18}/><strong>Review cover letter</strong><ArrowDown size={14}/></a><a className="application-step" href="#application-questions"><span>3</span><FileQuestion size={18}/><strong>Answer questions</strong><ArrowDown size={14}/></a><button className="application-step" type="button" disabled={downloading} onClick={downloadResume}><span>4</span><Download size={18}/><strong>{downloading?"Preparing…":"Download original format"}</strong></button>{job.sourceUrl?<a className="application-step primary-step" href={job.sourceUrl} target="_blank" rel="noreferrer"><span>5</span><ArrowUpRight size={18}/><strong>Open employer application</strong></a>:<span className="application-step disabled-step"><span>5</span><ArrowUpRight size={18}/><strong>Original posting unavailable</strong></span>}<button className="application-step" type="button" onClick={markApplied}><span>6</span><Send size={18}/><strong>Mark as applied</strong></button></div>{status?<div className={status.includes("downloaded")||status.startsWith("Marked")?"analysis-banner":"error-box"}><CheckCircle2 size={14}/> {status}</div>:null}</section></>;
}
