import { notFound } from "next/navigation";
import { ArrowUpRight, Download, Sparkles } from "lucide-react";
import { PageHead } from "@/components/ui";
import { getJob } from "@/lib/repositories/jobs";
import { getApplicationStudio } from "@/lib/ai/application-studio-generation";
import { CopyMessage } from "@/components/copy-message";
import { CustomApplicationQuestion } from "@/components/custom-application-question";
import { StudioWorkflow } from "@/components/studio-workflow";

export default async function StudioPage({params}:{params:Promise<{id:string}>}) {
  const {id}=await params; const job=await getJob(id); if(!job)notFound(); const studio=await getApplicationStudio(job);
  return <div className="content">
    <PageHead eyebrow="Application Studio" title={`${job.title} · ${job.company}`} copy="Review your tailored résumé, prepare the application and continue to the employer in one guided flow." action={<div className="actions">{job.sourceUrl?<a className="btn" href={job.sourceUrl} target="_blank" rel="noreferrer">View job posting <ArrowUpRight size={14}/></a>:null}<a className="btn primary" href={`/api/applications/studio/${job.id}/export`}><Download size={14}/>Download full pack</a></div>}/>
    <div className="grid metrics"><div className="metric"><div className="metric-label">Application quality</div><div className="metric-value">{studio.quality.score}/100</div><div className="metric-note">Review before submission</div></div><div className="metric"><div className="metric-label">Match score</div><div className="metric-value">{job.score}</div><div className="metric-note">{job.category}</div></div><div className="metric"><div className="metric-label">Evidence coverage</div><div className="metric-value">{studio.quality.checks[1].score}%</div><div className="metric-note">Verified requirements</div></div><div className="metric"><div className="metric-label">Integrity</div><div className="metric-value">{studio.quality.checks[2].score}%</div><div className="metric-note">No invented metrics</div></div></div>
    {job.sourceUrl?<aside className="job-source-strip"><span>Ready to submit on the employer’s website when your materials are complete.</span><a href={job.sourceUrl} target="_blank" rel="noreferrer">Open original job posting <ArrowUpRight size={14}/></a></aside>:<aside className="job-source-strip muted-source"><span>This demo role does not have an external posting. Imported and sourced jobs will show the original job link here.</span></aside>}
    <StudioWorkflow job={{id:job.id,title:job.title,company:job.company,sourceUrl:job.sourceUrl}} studio={studio}/>
    <section className="section card"><div className="section-head"><div><div className="eyebrow">Step 4 · Outreach</div><h2>Find the right people and prepare a personal message</h2><p className="subtle">ApplyIQ researches relevant public professional profiles and drafts grounded messages. Neelam reviews and sends everything manually.</p></div><a className="btn primary" href={`/contacts?job=${job.id}`}>Open outreach workspace <ArrowUpRight size={14}/></a></div></section>
    <div className="grid two-col section"><section className="card" id="cover-letter"><div className="section-head"><div><div className="eyebrow">Step 2 · Cover letter</div><h2>Personalized draft</h2></div><CopyMessage text={studio.coverLetter}/></div><p className="message-draft">{studio.coverLetter}</p></section><aside className="card"><div className="eyebrow">Quality review</div><h2>Before submitting</h2><div className="stack" style={{gap:10,marginTop:14}}>{studio.quality.checks.map(check=><div className="quality-row" key={check.label}><span><strong>{check.label}</strong><small>{check.recommendation}</small></span><b>{check.score}</b></div>)}</div></aside></div>
    <section className="section" id="application-questions"><div className="section-head"><div><div className="eyebrow">Step 3 · Application questions</div><h2>Prepared answers</h2><p className="subtle">Factual starting points for common questions.</p></div><Sparkles color="var(--green)"/></div><div className="stack">{studio.answers.map(item=><article className="card" key={item.question}><div className="section-head"><h3>{item.question}</h3><CopyMessage text={item.answer}/></div><p>{item.answer}</p></article>)}<CustomApplicationQuestion jobId={job.id}/></div></section>
  </div>;
}
