import "server-only";
import { createHash } from "node:crypto";
import { z } from "zod";
import { buildInterviewPrep } from "@/lib/interview-prep";
import { getCachedGeneration, saveGeneration } from "@/lib/repositories/ai-generations";
import { getLatestResumeText } from "@/lib/repositories/resumes";
import type { InterviewRecord } from "@/lib/repositories/interviews";
import type { Job } from "@/lib/types";

const prepSchema=z.object({roleSummary:z.string(),companySummary:z.string(),lookingFor:z.array(z.string()),whyFit:z.array(z.string()),concerns:z.array(z.string()),questions:z.array(z.object({question:z.string(),answer:z.string()})),star:z.array(z.object({title:z.string(),situation:z.string(),task:z.string(),action:z.string(),result:z.string()})),questionsToAsk:z.array(z.string()),interviewerResearch:z.string(),companySources:z.array(z.object({title:z.string(),url:z.string().url()})).max(8)});
const schema={type:"object",additionalProperties:false,properties:{roleSummary:{type:"string"},companySummary:{type:"string"},lookingFor:{type:"array",items:{type:"string"}},whyFit:{type:"array",items:{type:"string"}},concerns:{type:"array",items:{type:"string"}},questions:{type:"array",items:{type:"object",additionalProperties:false,properties:{question:{type:"string"},answer:{type:"string"}},required:["question","answer"]}},star:{type:"array",items:{type:"object",additionalProperties:false,properties:{title:{type:"string"},situation:{type:"string"},task:{type:"string"},action:{type:"string"},result:{type:"string"}},required:["title","situation","task","action","result"]}},questionsToAsk:{type:"array",items:{type:"string"}},interviewerResearch:{type:"string"},companySources:{type:"array",items:{type:"object",additionalProperties:false,properties:{title:{type:"string"},url:{type:"string"}},required:["title","url"]}}},required:["roleSummary","companySummary","lookingFor","whyFit","concerns","questions","star","questionsToAsk","interviewerResearch","companySources"]};

export async function getInterviewPrep(interview:InterviewRecord,job:Job){
  const fallback={...buildInterviewPrep(job),companySources:[] as Array<{title:string;url:string}>};const resume=await getLatestResumeText();
  if(!process.env.OPENAI_API_KEY||!resume)return fallback;
  const fingerprint=createHash("sha256").update(JSON.stringify({resume,job,stage:interview.stage,interviewer:interview.interviewer})).digest("hex");
  const cached=await getCachedGeneration<z.infer<typeof prepSchema>>("interview",interview.id,"interview_prep",fingerprint);if(cached)return cached;
  try{const response=await fetch("https://api.openai.com/v1/responses",{method:"POST",headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,"Content-Type":"application/json"},body:JSON.stringify({model:process.env.OPENAI_MODEL||"gpt-5.6-luna",store:false,tools:[{type:"web_search"}],instructions:"Create a rigorous interview pack. Research the company from current reliable public sources, prioritizing its official site and reputable recent reporting. Separate verified facts from inference. Ground every model answer and STAR example only in the supplied résumé; never invent actions, metrics, qualifications or skills. Questions must reflect the exact role requirements and interview stage. Answers must be natural first-person model answers, not instructions. Research an interviewer only from supplied public professional facts; otherwise state that it is incomplete. Return direct source URLs for company claims.",input:`INTERVIEW:\n${JSON.stringify(interview)}\n\nJOB:\n${JSON.stringify(job)}\n\nLATEST RÉSUMÉ:\n${resume}`,text:{format:{type:"json_schema",name:"interview_prep",strict:true,schema}}})});if(!response.ok)throw new Error(`OpenAI interview preparation failed (${response.status})`);const data=await response.json() as {output_text?:string};const prep=prepSchema.parse(JSON.parse(data.output_text||"{}"));await saveGeneration("interview",interview.id,"interview_prep",fingerprint,prep);return prep}catch(error){console.error("AI interview preparation fallback",error);return fallback}
}
