import { notFound } from "next/navigation";
import { CalendarClock, ExternalLink, ShieldCheck } from "lucide-react";
import { PageHead } from "@/components/ui";
import { getInterview } from "@/lib/repositories/interviews";
import { getInterviewPrep } from "@/lib/ai/interview-prep-generation";
import { InterviewOutcome } from "@/components/interview-outcome";

export default async function InterviewPrepPage({params}:{params:Promise<{id:string}>}){
  const {id}=await params;const record=await getInterview(id);if(!record)notFound();
  const {interview,job}=record;const prep=await getInterviewPrep(interview,job);
  return <div className="content"><PageHead eyebrow="Step 4 · AI interview pack" title={`${job.company} · ${interview.stage||interview.type}`} copy={`${job.title} · ${new Date(interview.startsAt).toLocaleString()}${interview.interviewer?` · ${interview.interviewer}`:""}`}/>
    <div className="analysis-banner" style={{display:"flex",gap:8,alignItems:"center",marginBottom:18}}><ShieldCheck size={15}/> Company facts use current public research. Every model answer is grounded in Neelam’s latest résumé.</div>
    <div className="grid two-col"><section className="stack"><article className="card"><div className="eyebrow">Role and company brief</div><p>{prep.roleSummary}</p><p>{prep.companySummary}</p><h3>What they are looking for</h3><ul className="list">{prep.lookingFor.map(item=><li key={item}>{item}</li>)}</ul></article><article className="card"><div className="eyebrow">Why Neelam fits</div><ul className="list">{prep.whyFit.map(item=><li key={item}>{item}</li>)}</ul><h3 style={{marginTop:18}}>Likely concerns</h3><ul className="list">{prep.concerns.map(item=><li key={item}>{item}</li>)}</ul></article><article className="card"><div className="eyebrow">Likely questions and model answers</div>{prep.questions.map(item=><div className="prep-question" key={item.question}><h3>{item.question}</h3><p>{item.answer}</p></div>)}</article></section>
      <aside className="stack"><article className="card"><div className="eyebrow">Interviewer research</div><p>{prep.interviewerResearch}</p></article><article className="card"><div className="eyebrow">Questions Neelam can ask</div><ul className="list">{prep.questionsToAsk.map(item=><li key={item}>{item}</li>)}</ul></article><article className="card"><div className="eyebrow">Research sources</div>{prep.companySources.length?<ul className="list">{prep.companySources.map(source=><li key={source.url}><a href={source.url} target="_blank" rel="noreferrer">{source.title} <ExternalLink size={12}/></a></li>)}</ul>:<p className="subtle">Live company research was unavailable; verify company claims before the interview.</p>}</article><article className="card"><div className="section-head"><div><div className="eyebrow">Interview details</div><h3>{interview.type}</h3></div><CalendarClock color="var(--green)"/></div><p className="subtle">{new Date(interview.startsAt).toLocaleString()}<br/>{interview.interviewerTitle||"Interviewer title not recorded"}</p></article></aside></div>
    <section className="section"><div className="section-head"><div><h2>Verified STAR model answers</h2><p className="subtle">Practice these naturally; every fact comes from the latest résumé.</p></div></div><div className="grid two-col">{prep.star.map(item=><article className="card" key={item.title}><h3>{item.title}</h3><dl className="star-grid"><dt>Situation</dt><dd>{item.situation}</dd><dt>Task</dt><dd>{item.task}</dd><dt>Action</dt><dd>{item.action}</dd><dt>Result</dt><dd>{item.result}</dd></dl></article>)}</div></section>
    <InterviewOutcome id={interview.id} company={job.company} role={job.title} interviewer={interview.interviewer} initialOutcome={interview.outcome} initialNotes={interview.notes}/>
  </div>;
}
