import { notFound } from "next/navigation";
import Link from "next/link";
import { getJob } from "@/lib/repositories/jobs";
import { CategoryPill, PageHead } from "@/components/ui";
import { getApplicationRecord } from "@/lib/repositories/applications";
import { ApplicationRecord } from "@/components/application-record";
import { JobFeedback } from "@/components/job-feedback";
import { StartApplicationButton } from "@/components/start-application-button";
import { ReanalyzeJobButton } from "@/components/reanalyze-job-button";
import { RequirementsMatrix } from "@/components/requirements-matrix";
import { getRoleOverview } from "@/lib/ai/role-overview";
import { Suspense } from "react";

async function RoleOverview({job}:{job:NonNullable<Awaited<ReturnType<typeof getJob>>>}){const roleOverview=await getRoleOverview(job);return <section className="card role-at-glance"><div className="eyebrow">Role at a glance</div><h2>What this role is</h2><ul className="list">{roleOverview.map(item=><li key={item}>{item}</li>)}</ul></section>}
function applicationStrategy(job:NonNullable<Awaited<ReturnType<typeof getJob>>>){const strongest=job.strengths[0]||`relevant ${job.roleFamily.toLowerCase()} experience`;const priority=job.requirements.find(item=>item.importance==="Required")?.requirement;const gap=job.gaps[0];return [`Lead with ${strongest.charAt(0).toLowerCase()}${strongest.slice(1)}`,priority?`Make the evidence for “${priority}” easy to find in the résumé and application answers.`:`Make the strongest role-relevant evidence easy to find in the résumé.`,gap?`Address this gap honestly without overstating experience: ${gap}`:"Keep every claim specific, factual and supported by the latest résumé."]}

export default async function JobDetail({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params; const job = await getJob(id); if (!job) notFound();const application=await getApplicationRecord(id);
  return <div className="content"><PageHead eyebrow={`${job.company} · ${job.location}`} title={job.title} copy={`${job.arrangement} · ${job.salary ?? "Salary not listed"} · Posted ${job.postedDaysAgo} days ago`} action={<Link className="btn" href="/jobs">Back to jobs</Link>}/><section className="card next-step-card"><div><div className="eyebrow">Your recommended next step</div><h2>Prepare this application</h2><p className="subtle">Tailor the résumé, prepare answers and create the application pack.</p></div><div className="next-step-actions"><StartApplicationButton jobId={job.id}/><Link className="text-action" href={`/contacts?job=${job.id}`}>Or find a relevant contact</Link></div><details className="more-actions"><summary>More actions</summary><div className="actions"><ReanalyzeJobButton jobId={job.id}/><JobFeedback jobId={job.id}/></div></details></section><Suspense fallback={<section className="card role-at-glance loading-card"><div className="eyebrow">Role at a glance</div><p>Preparing a concise overview…</p></section>}><RoleOverview job={job}/></Suspense><div className="detail-grid"><div className="stack">
    <details className="card guided-section" open><summary><span><small>Step 1</small><strong>Review the ApplyIQ assessment</strong></span><em>Open</em></summary><div className="guided-section-body"><p>{job.summary}</p><div className="grid two-col"><div><h3>Why you fit</h3><ul className="list">{job.strengths.map(s=><li key={s}>{s}</li>)}</ul></div><div><h3>Potential gaps</h3><ul className="list">{job.gaps.map(s=><li key={s}>{s}</li>)}</ul></div></div></div></details>
    <details className="card guided-section"><summary><span><small>Step 2</small><strong>Check candidate requirements</strong></span><em>{job.requirements.length} requirements</em></summary><div className="guided-section-body"><p className="subtle">Only explicit qualifications from the posting, checked against the latest résumé.</p><RequirementsMatrix requirements={job.requirements}/></div></details>
    <details className="card guided-section"><summary><span><small>Step 3</small><strong>Review your application strategy</strong></span><em>Job-specific</em></summary><div className="guided-section-body"><ul className="list">{applicationStrategy(job).map(item=><li key={item}>{item}</li>)}</ul></div></details>
    <ApplicationRecord jobId={job.id} initial={application}/>
  </div><aside className="stack"><div className="card match-card"><span className="match-label">ApplyIQ match</span><div className="score-ring" style={{"--score":`${job.score}%`} as React.CSSProperties} data-score={job.score}/><CategoryPill category={job.category}/><div className="probability"><span>Estimated interview probability</span><strong>{job.probability}%</strong></div><p className="estimate-note">Directional estimate based on your verified experience and the role requirements.</p></div><div className="card"><h3>Source</h3><p className="subtle">{job.source}</p>{job.sourceUrl?<a className="btn" href={job.sourceUrl} target="_blank" rel="noreferrer" style={{marginTop:14}}>View original posting</a>:null}</div></aside></div></div>;
}
